name: construction_site
geometry_dimensions:
  h_min: 10
  h_max: 120
  x_min: -120
  x_max: 90
  y_min: -120
  y_max: 120
fibonacci_radius_list: [20, 40, 60, 80, 100]
dense_factor: 16
star_sampling:
  min_radius: 10
  max_radius: 81