name: hospital
geometry_dimensions:
  h_min: 10
  h_max: 120
  x_min: -200
  x_max: 220
  y_min: -230
  y_max: 200
fibonacci_radius_list: [130] #80, 100, 120, 140, 160, 180, 200
dense_factor: 2048
star_sampling:
  min_radius: 10
  max_radius: 200 # 200

# hospital dimensions: height_min = 1, height_max = 150, x_min=-200, x_max = 220, y_min = -230, y_max =200
