name: hartly_mansion
geometry_dimensions:
  h_min: 10
  h_max: 90
  x_min: -60  
  x_max: 60
  y_min: -60
  y_max: 60
fibonacci_radius_list: [20, 40, 60, 80]
dense_factor: 16
star_sampling:
  min_radius: 10
  max_radius: 91

# gragen of eden dimensions: h_min = 10, h_max = 120, x_min = -90, x_max = 90, y_min = -80, y_max = 80
