name: random_terrian
geometry_dimensions:
  h_min: 10
  h_max: 300
  x_min: -300
  x_max: 400
  y_min: -350
  y_max: 600
fibonacci_radius_list: [100, 150, 200, 250, 300]
dense_factor: 256
star_sampling:
  min_radius: 10
  max_radius: 81