name: baseball_stadium
geometry_dimensions:
  h_min: 1
  h_max: 120
  x_min: -120
  x_max: 90
  y_min: -70
  y_max: 90
fibonacci_radius_list: [20, 40, 60, 80]
dense_factor: 16
star_sampling:
  min_radius: 10
  max_radius: 91

# baseball stadium dimensions: x_min=-95, x_max = 175, y_min = -120, y_max = 120