name: five_skyscrapers
geometry_dimensions:
  h_min: 10
  h_max: 300
  x_min: -220
  x_max: 180
  y_min: -200
  y_max: 200
fibonacci_radius_list: [60, 80, 100, 120, 140, 160, 180, 200]
dense_factor: 64
star_sampling:
  min_radius: 10
  max_radius: 201