name: small_mill
geometry_dimensions:
  h_min: 10
  h_max: 120
  x_min: -100
  x_max: 85
  y_min: -90
  y_max: 100
fibonacci_radius_list: [20, 40, 60, 80, 100]
dense_factor: 16
star_sampling:
  min_radius: 10
  max_radius: 81