name: wood_island
geometry_dimensions:
  h_min: 10
  h_max: 120
  x_min: -70
  x_max: 70
  y_min: -90
  y_max: 90
fibonacci_radius_list: [20, 40, 60, 80, 100]
dense_factor: 16
star_sampling:
  min_radius: 10
  max_radius: 91

# gragen of eden dimensions: h_min = 10, h_max = 120, x_min = -90, x_max = 90, y_min = -80, y_max = 80
